REGION="berlin"

MAX_SPEED_DEFAULT={"rail":100}
MAX_COMPLETION_THRESHOLD={"rail":0.05}

MAX_STATION_DISTANCE_THRESHOLD_CONNECTION={"rail":0.3}
MAX_STATION_DISTANCE_THRESHOLD_CONNECTION={"rail":0.1}

MAX_STATION_DISTANCE_THRESHOLD={"rail":0.5}
MAX_STATION_DISTANCE_THRESHOLD_HIGHLYSIMILARNAME=0.6
MAX_STATION_DISTANCE_THRESHOLD_IDENTICALNAME=1.0



